name: 'Automatically add issue into Kanban'

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Move issues into pj column
        uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: カンバン
          column: いつかやる
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
